force-app/main/default/objects/Mock_Expense_Data__c/Mock_Expense_Data__c.object-meta.xml
<CustomObject>
    <label>Mock_Expense_Data</label>
    <nameField>
        <label>Mock_Expense_Data</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mock_Expense_Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mock_Expense_Data__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mock_Expense_Data__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CharController.cls
public with sharing class CharController {
    @AuraEnabled
    public static List<Mock_Expense_Data__c> getExpenses(Date startDate, Date endDate){
        return [select Id, Expense_Type__c, Amount__c, Expense_Date__c from Mock_Expense_Data__c where Expense_Date__c >= :startDate and Expense_Date__c<=: endDate];
    }

    @AuraEnabled
    public static void saveImage(String fileName, String base64Str){

        ContentVersion cv = new ContentVersion();
        cv.Title = fileName;
        cv.PathOnClient = fileName;
        cv.VersionData = EncodingUtil.base64Decode(base64Str);

        insert cv;
    }
}